project:
  type: book

book:
  title: "Démo du package Tabloid"
  author: "Rémi Dumas"
  date: "22/05/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - exercices.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - sandstone
      - brand




